language: scala
scala:
   - 2.11.6
branches:
    only:
      - master
      - dev

script:
    - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
    - sbt ++$TRAVIS_SCALA_VERSION coveralls
